project:
  type: website

website:
  title: "Learning R and Python"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  sidebar:
    #style: "docked"
    search: true
    contents:
      - section: "Basics"
        contents:
          - index.qmd
          - exploration.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



